### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by khanghoang** [paramaggarwal/rn-paper-interface#1]
Thanks for sharing this, my question is does it work on Android?
I just checked the `index.android.js` but there was react-native template code :(
Let me know if you have plan to support Android.

**Comment by paramaggarwal** [comment]
I have not tried it on Android. It seems like it could run on Android too as I haven't used any iOS specific things. You can try copying the contents of `index.ios.js` into `index.android.js` and giving it a shot!

Feel free to open a PR once someone gets it to run on Android.

**Comment by paramaggarwal** [comment]
I tried running it as is on Android - the pan gestures are not working as expected. The cards zoom up but then on release they just stay there... Anyone aware of the quirks on Android regarding this?

**Comment by michaelspeed** [comment]
did you manage to fix the issue with android?

and while expanding the paper does not switch to full screen height. there is a small amount of space left at the top? how to change that?
