### ISSUE TITLE
Native driver

### ISSUE THREAD

**Issue by emrosenf** [paramaggarwal/rn-paper-interface#2]
Awesome work! Just reminding you that spring animations are currently supported natively in iOS, and there is a pending [pull request for Android](https://github.com/facebook/react-native/pull/8860). In real world applications, this may boost perceived performance.

Edit: added link to PR for more visibility

**Comment by paramaggarwal** [comment]
Oh nice, that means that folks using the `Animated` library for their app will slowly see performance improvements as more and more of it is handled purely in native. Exciting!
